###The created R script is used for the Getting and Cleaning Data Course Project.

## Set up the working directory
setwd(getwd())

## load packages
library(plyr); library(dplyr)
library(tidyr); library(data.table)

## Download and unzip the zipped file into a temporary folder 
temp <- tempfile()
fileURL1 <- "https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip"
download.file(fileURL1, temp, mode = "wb")
unzip(temp, exdir = ".", list = TRUE)

## Select and read files from the list generated by unzip
activity_labels <- read.table(unzip(temp, "UCI HAR Dataset/activity_labels.txt"))
features <- read.table(unzip(temp, "UCI HAR Dataset/features.txt"))

featureval_test <- read.table(unzip(temp, "UCI HAR Dataset/test/X_test.txt"))
subject_test <- read.table(unzip(temp, "UCI HAR Dataset/test/subject_test.txt"))
activity_test <- read.table(unzip(temp, "UCI HAR Dataset/test/y_test.txt"))

featureval_train <- read.table(unzip(temp, "UCI HAR Dataset/train/X_train.txt"))
subject_train <- read.table(unzip(temp, "UCI HAR Dataset/train/subject_train.txt"))
activity_train <- read.table(unzip(temp, "UCI HAR Dataset/train/y_train.txt"))

unlink(temp)

## Data Cleaning
# Cleaning test files by adding variable names, subject and activity
colnames(featureval_test) <- tolower(features[, 2])
colnames(subject_test) <- "subject"
colnames(activity_test) <- "activity"
data_test <- data.frame(cbind(subject_test, activity_test, featureval_test))

# Cleaning train files by adding variable names, subject and activity
colnames(featureval_train) <- tolower(features[, 2])
colnames(subject_train) <- "subject"
colnames(activity_train) <- "activity"
data_train <- data.frame(cbind(subject_train, activity_train, featureval_train))
                         
## Assignment task 1: Merges the training and the test sets to create one data set.
data_all <- rbind(data_train, data_test)

## Assigment Task 2: Extracts only the measurements on the 
## mean and standard deviation for each measurement.
isMean <- grep("*mean*" , colnames(data_all)) 
isStd <- grep("*std*", colnames(data_all)) 
data_select <- data_all[, c(1, 2, isMean, isStd)] #1 for subject and 2 for activity
dim(data_select)

## Assignment task 3: Descriptively name the activities in the data set by factorizing 
## the Variable activity in the data frame data_select
data_select$activity <- factor(data_select$activity,
                              levels = activity_labels$V1,
                              labels = activity_labels$V2)

## Assignment task 4: Label the data set with descriptive variable names
names(data_select) <- gsub("^t", "time", names(data_select))
names(data_select) <- gsub("tbody", "timebody", names(data_select))
names(data_select) <- gsub("^f", "frequency", names(data_select))
names(data_select) <- gsub("bodybody", "body", names(data_select))
names(data_select) <- gsub("acc", "Accelerator", names(data_select))
names(data_select) <- gsub("gyro", "Gyroscope", names(data_select))
names(data_select) <- gsub("mag", "Magnitude", names(data_select))


## Assignment tast 5: Create a second, independent tidy data set 
## with the average of each variable for each activity and each subject.
data_summary <- aggregate(. ~ subject + activity, data_select, mean)
tidydata.df <- arrange(data_summary, subject, activity)
write.table(tidydata.df, file = "tidydata.txt", row.name = FALSE)
